### PR TITLE
DelDiv feature implemented

### PR DESCRIPTION
**Pull request by Sn0wB**
Hi @dillionmegida !

I implemented a feature which delete a div! If you see any error or you found a bug let me know! :)

### CODE REVIEW

**Comment by dillionmegida** [comment]
Thank you so much for your contribution.
I'll let you know of any bugs.
Also, I am working towards attending to each div where they possess individual properties. You are welcome to share your ideas.

**Comment by dillionmegida** [comment]
And yes, no bugs : )

**Comment by Sn0wB** [comment]
@dillionmegida if you need help I can help you with the idea named "Individual resizing of the elements instead of a general size."

**Comment by dillionmegida** [comment]
That would be nice.
You can go on with that.
By the way, I just added the generate code button, it's now functional.
Testing it and also consider it when doing the individual resizing. : )

**Pull request merged**
